CREATE TABLE app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id VARCHAR(21) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE professional_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id VARCHAR(21) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL UNIQUE, description TEXT, active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE professionals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id VARCHAR(21) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL, business_name VARCHAR(150), description TEXT, phone VARCHAR(30), whatsapp VARCHAR(30),
  email VARCHAR(255), instagram VARCHAR(255), city VARCHAR(120), state VARCHAR(2), active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE professional_category_links (
  professional_id BIGINT NOT NULL REFERENCES professionals(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES professional_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (professional_id, category_id)
);
CREATE INDEX idx_app_users_public_id ON app_users(public_id); CREATE INDEX idx_app_users_active ON app_users(active);
CREATE INDEX idx_categories_public_id ON professional_categories(public_id); CREATE INDEX idx_categories_active ON professional_categories(active); CREATE INDEX idx_categories_slug ON professional_categories(slug);
CREATE INDEX idx_professionals_public_id ON professionals(public_id); CREATE INDEX idx_professionals_active ON professionals(active); CREATE INDEX idx_professionals_city ON professionals(city);
CREATE INDEX idx_professional_category_links_category ON professional_category_links(category_id);
